SECRET_KEY = "key"

LDAP_SERVER = "ldap://10.3.3.13:389"
LDAP_HOST = "tw.fpg.com"

AUTH = [
    "N000182222",
    "N000008216",
    "N000146728",
    "N000156879",
    "N000162032",
    "N000172913",
    "N000152378",
    "N000175122",
    "N000152393",
    "N000006735",
    "N000006924",
    "N000025735",
    "N000134055",
    "N000173059",
    "N000175297",
    "N000183456",
    "N000143911",
    "N000175110",
    "N000173055",
    "N000175111",
    "N000018225",
    "N000008933",
    "N000130115",
    "N000148912",
    "N000155642",
    "N000159761",
    "N000165170",
    "N000174156",
    "N000175896",
    "N000161878",
    "N000183062"
]

[TITLES]
    "fpc_engineer"="台塑工程會簡報清單"
    "fpc_ai"="台塑台北AI專案會簡報清單"
    "npc_engineer"="南亞工程會簡報清單"
    "npc_ai"="南亞台北AI專案會簡報清單"
    "npc_project"="南亞專案檢討會簡報清單"
    "fcfc_engineer"="台化工程會簡報清單"
    "fcfc_ai"="台化台北AI專案會簡報清單"
    "fcfc_project"="台化專案檢討會簡報清單"
    "fpcc_engineer"="塑化工程會簡報清單"
    "fpcc_ai"="塑化台北AI專案會簡報清單"

[REPORTS]
    [[REPORTS.fpc_engineer]]
        date="2022/05/16"
        file="台塑/工程會/20220516 氫氟酸自動取樣影像辨識(工程會)"
        title="氫氟酸自動取樣影像辨識"
    [[REPORTS.fpc_engineer]]
        date="2020/09/26"
        file="台塑/工程會/20200926 油品雙烯值AI分析(工程會)"
        title="油品雙烯值AI分析"

    [[REPORTS.fpc_ai]]
        date="2022/10/26"
        file="台塑/AI報告/20221026麥寮正丁醇廠精餾塔AI操作最佳化"
        title="麥寮正丁醇廠精餾塔AI操作最佳化"
    [[REPORTS.fpc_ai]]
        date="2022/08/25"
        file="台塑/AI報告/20220825勝高矽晶圓自動兩面研磨平坦度預測系統"
        title="勝高矽晶圓自動兩面研磨平坦度預測系統"
    [[REPORTS.fpc_ai]]
        date="2021/09/16"
        file="台塑/AI報告/202109LLDPE-AI應用於轉品別最佳化控制"
        title="LLDPE-AI應用於轉品別最佳化控制"
    [[REPORTS.fpc_ai]]
        date="2020/11/13"
        file="台塑/AI報告/20201113ECH廠環氧氯丙烷(ECH)反應區收率優化"
        title="ECH廠環氧氯丙烷(ECH)反應區收率優化"
    [[REPORTS.fpc_ai]]
        date="2020/05/27"
        file="台塑/AI報告/20200527麥寮正丁醇廠異構物分離塔AI操作最佳化總裁報告"
        title="麥寮正丁醇廠異構物分離塔AI操作最佳化總裁報告"
    [[REPORTS.fpc_ai]]
        date="2019/09/27"
        file="台塑/AI報告/20190927VCM廠EDC精餾單元AI節能優化"
        title="VCM廠EDC精餾單元AI節能優化"

    [[REPORTS.npc_engineer]]
        date="2022/07/14"
        file="南亞/工程會/20220714 BPA再結晶回收優化報告(工程會)"
        title="BPA再結晶回收優化報告"
    [[REPORTS.npc_engineer]]
        date="2021/10/12"
        file="南亞/工程會/20211012 銅箔基板三廠工程會報告"
        title="銅箔基板三廠工程會報告"
    [[REPORTS.npc_engineer]]
        date="2020/11/23"
        file="南亞/工程會/20201123 工務部設備監控管理優化報告(工程會)"
        title="工務部設備監控管理優化報告"

    [[REPORTS.npc_ai]]
        date="2022/11/30"
        file="南亞/AI報告/20221130 電子部CCL含浸機製程管理作業優化"
        title="電子部CCL含浸機製程管理作業優化"
    [[REPORTS.npc_ai]]
        date="2022/05/24"
        file="南亞/AI報告/20220524 嘉義一廠硬管重量管制率優化"
        title="嘉義一廠硬管重量管制率優化"
    [[REPORTS.npc_ai]]
        date="2021/12/01"
        file="南亞/AI報告/20211201 BG廠總裁AI專案報告"
        title="BG廠總裁AI專案報告"
    [[REPORTS.npc_ai]]
        date="2020/12/25"
        file="南亞/AI報告/20201225 纖維部酯化聚合反應條件優化"
        title="纖維部酯化聚合反應條件優化"
    [[REPORTS.npc_ai]]
        date="2020/07/03"
        file="南亞/AI報告/20200703 電子部CCL外觀瑕疵檢查作業優化"
        title="電子部CCL外觀瑕疵檢查作業優化"
    [[REPORTS.npc_ai]]
        date="2019/10/25"
        file="南亞/AI報告/20191025 2EH廠OXO單元操作條件優化報告"
        title="2EH廠OXO單元操作條件優化報告"
    [[REPORTS.npc_ai]]
        date="2019/01/04"
        file="南亞/AI報告/20190104 提升產品瑕疵分類準確率報告"
        title="提升產品瑕疵分類準確率報告"

    [[REPORTS.npc_project]]
        date="2020/12/15"
        file="南亞/專案檢討會/20201215化二部BPA專案檢討會(AI部分)"
        title="化二部BPA專案檢討會(AI部分)"

    [[REPORTS.fcfc_engineer]]
        date="2022/11/13"
        file="台化/工程會/20221113 PP工程會(塑膠部智能工廠推動進度)"
        title="PP工程會(塑膠部智能工廠推動進度)"
    [[REPORTS.fcfc_engineer]]
        date="2022/07/18"
        file="台化/工程會/20220718 ARO3廠重組觸媒再生效能監控模組"
        title="ARO3廠重組觸媒再生效能監控模組"
    [[REPORTS.fcfc_engineer]]
        date="2022/03/14"
        file="台化/工程會/20220314_SM廠工程會_智能工廠推動進度報告"
        title="SM廠工程會_智能工廠推動進度報告"

    [[REPORTS.fcfc_ai]]
        date="2022/10/19"
        file="台化/AI報告/20221019 醋酸廠POx反應器進料單元最佳化操作"
        title="醋酸廠POx反應器進料單元最佳化操作"
    [[REPORTS.fcfc_ai]]
        date="2021/09/29"
        file="台化/AI報告/20210929 化一部開發輕油估價及效益最大化模組"
        title="化一部開發輕油估價及效益最大化模組"
    [[REPORTS.fcfc_ai]]
        date="2020/12/04"
        file="台化/AI報告/20201204 塑膠部麥寮PC廠雙酚A溶液濃度穩定控制優化"
        title="塑膠部麥寮PC廠雙酚A溶液濃度穩定控制優化"
    [[REPORTS.fcfc_ai]]
        date="2020/07/15"
        file="台化/AI報告/20200715 龍德PTA廠4-CBA品質控制優化"
        title="龍德PTA廠4-CBA品質控制優化"
    [[REPORTS.fcfc_ai]]
        date="2020/06/30"
        file="台化/AI報告/20220630 化二部合成酚廠異丙苯氧化反應產率優化應用"
        title="化二部合成酚廠異丙苯氧化反應產率優化應用"
    [[REPORTS.fcfc_ai]]
        date="2019/11/22"
        file="台化/AI報告/20191122 SM廠(海豐)脫氫觸媒性能預測及節能優化"
        title="SM廠(海豐)脫氫觸媒性能預測及節能優化"
    [[REPORTS.fcfc_ai]]
        date="2018/12/27"
        file="台化/AI報告/20181227 化一部開發萃取單元優化模組"
        title="化一部開發萃取單元優化模組"

    [[REPORTS.fcfc_project]]
        date="2022/09/16"
        file="台化/專案檢討會/20220916 化二部推動?位優化管?專題報告"
        title="化二部推動?位優化管?專題報告"
    [[REPORTS.fcfc_project]]
        date="2022/06/27"
        file="台化/專案檢討會/20220627 化一部開發效益最大化之各廠原料產品組合模組"
        title="化一部開發效益最大化之各廠原料產品組合模組"
    [[REPORTS.fcfc_project]]
        date="2022/05/18"
        file="台化/專案檢討會/20220518 工務部智能工廠AI執行報告"
        title="工務部智能工廠AI執行報告"
    [[REPORTS.fcfc_project]]
        date="2021/11/18"
        file="台化/專案檢討會/20211118 化三部數位工廠優化推動計畫"
        title="化三部數位工廠優化推動計畫"

    [[REPORTS.fpcc_engineer]]
        date="2021/11/15"
        file="塑化/工程會/20211115 CDU塔頂迴路管線內部腐蝕AI系統(工程會)"
        title="CDU塔頂迴路管線內部腐蝕AI系統"
    [[REPORTS.fpcc_engineer]]
        date="2020/07/13"
        file="塑化/工程會/20200713公用部汽電廠操作優化推動報告(工程會)"
        title="公用部汽電廠操作優化推動報告"

    [[REPORTS.fpcc_ai]]
        date="2022/08/18"
        file="塑化/AI報告/20220818 塑化公司烯烴部乙炔轉化器操作優化"
        title="塑化公司烯烴部乙炔轉化器操作優化"
    [[REPORTS.fpcc_ai]]
        date="2021/10/20"
        file="塑化/AI報告/20211020 麥寮廠區蒸汽電力調度管理優化報告"
        title="麥寮廠區蒸汽電力調度管理優化報告"
    [[REPORTS.fpcc_ai]]
        date="2021/02/02"
        file="塑化/AI報告/20210202 丙烯回收單元操作優化模組"
        title="丙烯回收單元操作優化模組"
    [[REPORTS.fpcc_ai]]
        date="2020/08/26"
        file="塑化/AI報告/20200826 塑化烯烴部輕油裂解爐操作優化"
        title="塑化烯烴部輕油裂解爐操作優化"
    [[REPORTS.fpcc_ai]]
        date="2019/12/20"
        file="塑化/AI報告/20191220 麥電公司鍋爐燃煤投入量優化"
        title="麥電公司鍋爐燃煤投入量優化"
    [[REPORTS.fpcc_ai]]
        date="2019/01/09"
        file="塑化/AI報告/20190109 常壓蒸餾單元操作優化模組"
        title="常壓蒸餾單元操作優化模組"
